name: CMake with Docker

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  BUILD_TYPE: Debug

jobs:
  build_release:
    runs-on: ubuntu:22.04
    name: Build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t sharcv4test-image

    - name: Create docker container
      run: docker create --name sharcv4test-container sharcv4test-image

    - name: Start docker container
      run: docker start sharcv4test-container

    - name: CMake configure
      run: docker exec sharcv4test-container cmake -B build -DCMAKE_BUILD_TYPE="Release"

    - name: Build
      run: docker exec sharcv4test-container cmake --build build --config Release

    - name: Check build status
      # Check the build status and return success or failure
      run: |
        if [ $? -eq 0 ]; then
          echo "Build succeeded"
        else
          echo "Build failed"
          exit 1
        fi
  build_server:
    runs-on: ubuntu:22.04
    name: Build Server and Test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t sharcv4test-image

    - name: Create docker container
      run: docker create --name sharcv4test-container sharcv4test-image

    - name: Start docker container
      run: docker start sharcv4test-container

    - name: CMake configure
      run: docker exec sharcv4test-container cmake -B build -DCMAKE_BUILD_TYPE="Server"

    - name: CMake Build
      run: docker exec sharcv4test-container cmake --build build

    - name: Check build status
      # Check the build status and return success or failure
      run: |
        if [ $? -eq 0 ]; then
          echo "Build succeeded"
        else
          echo "Build failed"
          exit 1
        fi
    
    - name: Run tests
      run: docker exec -w /workspace/build/ sharcv4test-container ctest -T test --output-on-failure
